
// actions should be performed in redux

export const ADD_EVENT = "ADD_EVENT";
export const GET_EVENTS = "GET_EVENTS"
export const GET_CURRENTUSER = 'GET_CURRENTUSER'
export const SIGN_OUT = 'SIGN_OUT'
export const UPDATE_USER = 'UPDATE_USER'
export const GET_MAPEVENTS = 'GET_MAPEVENTS'
export const LOAD_MORE_EVENTS = 'LOAD_MORE_EVENTS'
export const DELETE_EVENT = 'DELETE_EVENT'
export const GET_CREATEDEVENTS = 'GET_CREATEDEVENTS'
export const LOAD_MORE_CREATEDEVENTS = 'LOAD_MORE_CREATEDEVENTS'
export const GET_LIKEDEVENTS = 'GET_LIKEDEVENTS'
export const LOAD_MORE_LIKEDEVENTS = 'LOAD_MORE_LIKEDEVENTS'
export const GET_JOINEDEVENTS = 'GET_JOINEDEVENTS'
export const LOAD_MORE_JOINEDEVENTS = 'LOAD_MORE_JOINEDEVENTS'
export const ON_FOLLOW = 'ON_FOLLOW'
export const POST_COMMENT = 'POST_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const GET_COMMENT = 'GET_COMMENT'